### ISSUE TITLE
Terra Incognita no recepies for seeds

### ISSUE THREAD

**Issue by MAGGen-hub** [CodersDownUnder/FlowerSeeds#1]
1.16.5 version 36.1.36 forge
Terra Incognita mod problem.
For some reason I have no recepies for seeds from this mod. I mean they exist but there is no way to get them.
What I need to do to get seeds from this mod?

**Comment by Trhod17** [comment]
all you should have to do is place a flower and a wheat seed into the crafting table. can you give me the logs/debug.log file

**Comment by MAGGen-hub** [comment]
Are you sure? 
![image](https://user-images.githubusercontent.com/56871670/132833755-8664834a-9cbd-445e-a3cb-9d4d16b0d371.png)

I think I have lots of mod conflicts... 
[debug.log](https://github.com/CodersDownUnder/FlowerSeeds/files/7142859/debug.log)

Sorry for the mess in file...

**Comment by MAGGen-hub** [comment]
And yes. Blue Iris seeds is exist. But I can't craft them...

**Comment by MAGGen-hub** [comment]
No recepies in JEI...

**Comment by MAGGen-hub** [comment]
Eh... Well... How...

**Comment by MAGGen-hub** [comment]
[10сен2021 08:57:34.911] [Render thread/INFO] [net.minecraft.item.crafting.RecipeManager/]: Skipping loading recipe flowerseeds:yellow_primrose as it's serializer returned null

**Comment by MAGGen-hub** [comment]
[10сен2021 08:57:34.879] [Render thread/INFO] [net.minecraft.item.crafting.RecipeManager/]: Skipping loading recipe flowerseeds:foxglove as it's serializer returned null

Well... I think there is too much nulls.
I will try to debug it... I think it could be seasons mod problem or maybe farmersdelight (one of them posibly changed the seeds id)...

**Comment by MAGGen-hub** [comment]
No... Thats not mod conflicts...
Only tree mods:
terraincognita-1.16.3-1.7
flowerseeds-1.16.5-1.3.2
cuneiform-1.16.3-1.2.5 (required by terraincognita)
Same issue...

**Comment by MAGGen-hub** [comment]
Finaly. The recepies is not unlocked... And I can use only comand to unlook them... Like this:
/recipe give MAGGen flowerseeds:allium

**Comment by Trhod17** [comment]
downgrade terra incognita to the latest non beta version as they changed the name of a lot of there flowers

**Comment by MAGGen-hub** [comment]
Is this beta? Ok... Thanks...

**Comment by MAGGen-hub** [comment]
Well... Sorry... Downgrade to terraincognita-1.16.3-1.6.4.2 and... Same result... Meh... I more than sure that problem has better solution... I just create a recourse pack for my game that makes recepies avaliable... I will make a pull request with fixed recepie constructor if I got more time...
