### ISSUE TITLE
Loot Table Error on Server Start Up 

### ISSUE THREAD

**Issue by Tyronadre** [CodersDownUnder/FlowerSeeds#2]
mc 1.18.1
forge 39.0.10
mod 2.0.0

On Serverstartup the mod is spamming 
Couldn't parse loot table flowerseeds:blocks/crop_marigold
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'terraincognita:marigold'
and so on. 
We dont have terraincognita on the server.

**Comment by Trhod17** [comment]
bug with the recipe flag system shouldnt break anything

**Comment by Tyronadre** [comment]
It doesn't but it's not pretty to spam the console

**Comment by Trhod17** [comment]
Fixed in 1.18.2 V3.0.0
