### ISSUE TITLE
Add 'crops' tag to flower seeds

### ISSUE THREAD

**Issue by Dekamir** [CodersDownUnder/FlowerSeeds#3]
**Is your feature request related to a problem?**
Yes, compatibility.

**Describe the solution you'd like**
Add 'crops' tag to flower seed blocks.

**Additional context**
For example, one cannot use $crops to refer to flower seeds, unlike other crops in Minecraft (like carrots, wheat seeds).
Most mods use this to refer all crops. This may ease the compatibility labour.

**Comment by Trhod17** [comment]
Added in 1.18.2 V3.0.0
