### ISSUE TITLE
[1.18.2] Dandelion Seeds Wrong Flower Render

### ISSUE THREAD

**Issue by HalcyonSeas73** [CodersDownUnder/FlowerSeeds#4]
**Versions**
- Minecraft Version 1.18.2
- Forge Version 40.1.60
- Mod Version 3.0
- Resource Pack: Mizuno's

**Describe the bug**
Dandelion seeds grow into the visual appearance of an Allium flower (but drops dandelions properly when broken)

**To Reproduce**
1. Plant dandelion seeds into farmland
2. Let it grow
3. Fully grown dandelion seeds appear to be an allium flower, not dandelions
4. When harvested, dandelions are properly dropped

**Expected behavior**
Dandelion seeds should render dandelions

**Screenshots**
![Untitled2](https://user-images.githubusercontent.com/84727791/178565069-48906a95-97e2-4303-87bb-bd49022ab4b3.png)

**Comment by Trhod17** [comment]
Fixed in V3.0.1

https://www.curseforge.com/minecraft/mc-mods/flower-seeds/files/3876355
