### ISSUE TITLE
Compatibility issues with resource pack flowers

### ISSUE THREAD

**Issue by johanplima** [CodersDownUnder/FlowerSeeds#6]
**Is your feature request related to a problem? Please describe.**
mod compatibility https://www.planetminecraft.com/texture-pack/better-flowers-3d/

**Describe the solution you'd like**
I don't understand why it doesn't work, but when I use the seed, Vanilla flowers appear, instead of pack ones 

**Describe alternatives you've considered**
I would love if that works <3

**Additional context**
using 1.18.2 MC
forge 40.1.73

**Comment by Trhod17** [comment]
That resource pack dosent override the vanilla textures, but rather replaces the models and uses its own textures, with different names. theres not much i can do really unless someone where to make a compatibility resource pack to replace the models in my mod.
